version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bank_cards_postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_cards_app
    environment:
      DB_HOST: bank_cards_postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank_cards_postgres:5432/bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '0000'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mySuperSecretKeyForJWTBankCardSystem2024ThatIsVeryLongAndSecure
      APP_ENCRYPTION_SECRET: MyBankCardEncryptionKey123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge